name: infinity_notes
description: "Infinity Notes app."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.8.1

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  firebase_core: ^4.0.0
  firebase_auth: ^6.0.1
  cloud_firestore: ^6.0.0
  firebase_storage: ^13.0.0
  rename_app: ^1.6.5
  google_sign_in: ^7.1.1
  sign_in_with_apple: ^7.0.1
  sqflite: ^2.4.2
  path_provider: ^2.1.5
  path: ^1.9.1
  flutter_staggered_grid_view: ^0.6.2
  share_plus: ^11.1.0
  bloc: ^9.0.0
  flutter_bloc: ^9.1.1
  equatable: ^2.0.3


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  flutter_native_splash: 2.4.6
  flutter_launcher_icons: 0.14.4
  test: ^1.25.15

flutter:
  uses-material-design: true
  assets:
    - assets/icons/
    - assets/images/

# ---- Splash screen ----
flutter_native_splash:
  color: "#3993ad"
  image: assets/icons/Infinity_Notes_Icon.png
  android: true
  ios: true
  android_gravity: center


# ---- App icons ----
flutter_launcher_icons:
  android: true
  ios: true
  image_path: assets/icons/Infinity_Notes_Icon.png
  adaptive_icon_background: "#3993ad"
  adaptive_icon_foreground: assets/icons/Infinity_Notes_Icon.png
  adaptive_icon_foreground_padding: 20  # prevents icon from zooming
